### ISSUE TITLE
Share pretrained models in Hugging Face

### ISSUE THREAD

**Issue by osanseviero** [venture-anime/cartoongan-pytorch#2]
Hello!

I saw your Space for [AnimeBackgroundGAN](https://huggingface.co/spaces/akiyamasho/AnimeBackgroundGAN) in HF Spaces and it's very cool! At the moment, I see the models are stored in a `models/` directory in the Spaces repo. 

We are encouraging hosting the model weights in model repositories instead of having them directly in the spaces. By having 4 model repositories, you will make them discoverable and allow other people that might want to use them to leverage them! You can also add a model card and tags to make them much more discoverable. The process is the same as you did for the Space, but here is a guide if it's useful https://huggingface.co/docs/hub/adding-a-model.

You can use the `huggingface_hub` library to load and cache the model from the Space or from any other place, as in the following example https://huggingface.co/spaces/akhaliq/JoJoGAN/blob/main/app.py#L39-L40. Another benefit is that you can just use the weights from the repos at https://github.com/venture-anime/cartoongan-pytorch/blob/main/pretrained_model/download_pth.sh

cc @NimaBoscarino @AK391 @julien-c

**Comment by akiyamasho** [comment]
@osanseviero Thanks for the examples!
I was able to add the pre-trained model files to a public model page successfully:
https://huggingface.co/akiyamasho/AnimeBackgroundGAN

After that, I tried loading it into the Space:
https://huggingface.co/spaces/akiyamasho/AnimeBackgroundGAN_staging/blob/main/app.py#L35-L45

However, whenever I download it in the actual space, it always gives back a 403 error:
```
Traceback (most recent call last):
  File "app.py", line 42, in <module>
    shinkai_model_hfhub = hf_hub_download(repo_id=MODEL_REPO_ID, filename=MODEL_FILE_SHINKAI)
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 533, in hf_hub_download
    return cached_download(
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 467, in cached_download
    http_get(
  File "/home/user/.local/lib/python3.8/site-packages/huggingface_hub/file_download.py", line 274, in http_get
    r.raise_for_status()
  File "/home/user/.local/lib/python3.8/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cdn-lfs.huggingface.co/repos/3b/28/3b282ada5ebaf8d74c671df28dcdca7f42ae6b587975e7bdea19b7ea2e1c5beb/c3547f611e780e79aebde7f7bc2b6c278555d701620f125583d666351044c486
```

Tried the following but to no avail (same error message):
1. Put my HF access token as a secret in the space and use it in the `use_auth_token` parameter
2. Try hardcoding the `repo_id` and `filename` (with and without the

I reverted the [original Space](https://huggingface.co/spaces/akiyamasho/AnimeBackgroundGAN) and setup this [staging Space](https://huggingface.co/spaces/akiyamasho/AnimeBackgroundGAN_staging) for now.
I'll be back to debug this at another time, but if you have any ideas on what might have happened, I'd love to hear them out.

**Comment by NimaBoscarino** [comment]
@akiyamasho Thanks for uploading the models! Hmm, that's so strange 🤔  Even when I try to [manually download](https://huggingface.co/akiyamasho/AnimeBackgroundGAN/blob/main/shinkai_makoto.pth) the `.pth` file, I get an "Access Denied" error. It's possible that something went wrong with the Git LFS, so I'll pass this by the Hub team and I'll come back to you with an update soon!

**Comment by NimaBoscarino** [comment]
So according to the Hub team it's possible that something went wrong when uploading the LFS files! Amon the things that could cause that, running `git push --no-verify` for example bypasses LFS files upload, leading to the error you're seeing.

One "simple" way to try to fix that is to try to push to a new repo. Another a bit more "advanced" would be to create a branch on a previous commit, force-push it on main on origin, checkout the local main branch again, and push again (I haven't tested this, but it should work).

For us though, I reuploaded your models here (https://huggingface.co/NimaBoscarino/AnimeBackgroundGAN) and I'm able to access them. If you want to delete your model from the Hub, I can transfer my model repo over to your account and we can restart the space and hopefully it should all work 😄

**Comment by osanseviero** [comment]
This is amazing, thanks @NimaBoscarino and @akiyamasho!!

By the way, we usually have one model per repository as a usual good practice with model repos. Do you think it would make sense to split this into 4, with each of the models in a different repo?

See how JoJoGan repo loads different models from different repos https://huggingface.co/spaces/akhaliq/JoJoGAN/blob/main/app.py#L122

**Comment by akiyamasho** [comment]
@NimaBoscarino Thanks for setting up the reuploaded model repo! 
I tried it on the staging Space and it worked perfectly.

As @osanseviero mentioned, I agree that it's best to keep the four models separately, so I created the four model repositories,

- [Makoto Shinkai](https://huggingface.co/akiyamasho/AnimeBackgroundGAN-Shinkai)
- [Mamoru Hosoda](https://huggingface.co/akiyamasho/AnimeBackgroundGAN-Hosoda)
- [Satoshi Kon](https://huggingface.co/akiyamasho/AnimeBackgroundGAN-Kon)
- [Hayao Miyazaki](https://huggingface.co/akiyamasho/AnimeBackgroundGAN-Miyazaki)

and updated it on the production version of the [AnimeBackgroundGAN Space](https://huggingface.co/spaces/akiyamasho/AnimeBackgroundGAN).
- [Source](https://huggingface.co/spaces/akiyamasho/AnimeBackgroundGAN/blob/main/app.py#L35-L51)

The space is running well and I made the staging environment private now.
Thanks so much!

I also added both of you to the Special Thanks section of the model repositories.
Let me know if these changes are ok and I'll close this Issue once everything looks good.

**Comment by akiyamasho** [comment]
PS: I updated the [README of this repository](https://github.com/venture-anime/cartoongan-pytorch#hugging-face-spaces-demo) to link to both the [Space](https://huggingface.co/spaces/akiyamasho/AnimeBackgroundGAN) and the [GitHub repository for the actual space codebase](https://github.com/venture-anime/anime-background-gan-hf-space), linked with GitHub actions to auto-update on push.

**Comment by osanseviero** [comment]
Super exciting! Thanks @akiyamasho! Love the space!

And thanks for adding us in the special thanks section and adding the links to the space! cc @julien-c It's also exciting you're using the GH workflow with auto-update on push! Super nice work! 

Should we close this issue? 🤗

**Comment by akiyamasho** [comment]
@osanseviero Thanks as well!

> Should we close this issue? 🤗

Will do 😁

**Comment by julien-c** [comment]
wow this is really cool, @akiyamasho!

And thanks @NimaBoscarino @osanseviero for helping this is awesome

**Comment by NimaBoscarino** [comment]
Excellent, glad it's all fixed up and the new model repos look great! I'll take down my mirrored repo.
